// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGXn28el44V2-6vmDJYx5KqSLAnVFzv_s',
    appId: '1:716900040199:web:f884b690815737ce5134a2',
    messagingSenderId: '716900040199',
    projectId: 'mynotes-flutter',
    authDomain: 'mynotes-flutter.firebaseapp.com',
    storageBucket: 'mynotes-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpaFarAKvMHXxJ925Jgjf9pRiTnyycPQs',
    appId: '1:716900040199:android:7d7e7b8bedf68abc5134a2',
    messagingSenderId: '716900040199',
    projectId: 'mynotes-flutter',
    storageBucket: 'mynotes-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO-r7R6YNkI_Csf30f4GnIXUOqh5fZv3I',
    appId: '1:716900040199:ios:b6b79b87aee05aaa5134a2',
    messagingSenderId: '716900040199',
    projectId: 'mynotes-flutter',
    storageBucket: 'mynotes-flutter.appspot.com',
    iosClientId: '716900040199-94l9m4s3vr22obciuobj6gllcme3f8jr.apps.googleusercontent.com',
    iosBundleId: 'com.mobasshir.mynotes',
  );
}
